---
.travis.yml:
  secure: "yYbIYSsGIj8d9FSK9cBnFr5VOeoqD+afEQ+88GTtVB2pgk04Foo3eyjydvXkwGkXzgWjOXVce8SJZb4fNdZBULSizgPXE9Q6yajwZn+jSDC5G+PC+2Yk7RPOooH7qifcLQHHxz/hie/LXzuiC5nUVMtirQIH3/3e2XYQcVtk5iORLjIfMAvuCAtuuvDjYfpStJuJXD5EGoG0zT6TEXLTAZO5YtjLZc5nHfWVJqtkthZs4ohu4ybhzdlI6QYREAWCpaxx9euFOIPY1uTfcwGNiXfYAbVwG14W7oSwae0P36CzFQrJ7UmmEPIn5AidY3yb1ZCn7Gx9iFo1xjrhv2S6DzvMEthj8R5iQaJF5UwKxG1mKguFoiwuQnsTHxcgMx0nIgd1cnh/4S5mkMafUrrR3Xog+bpDLteM3Mag+owfEACrxm4CshPR146PaFl05mwmYPk9zdx412c9V8+0afo9WKStEymXfs8DMi/AbjhDtNUEjjxBQphORxzyDb3+LJA22JU1D7izqZEZPN3O2wAw9AQrRhVWIThp5rxgj/TgJUBGCsm2i72OC+KgXrhJhaRcHVY0P4xSG/GvwfyR6jaSgA2qn8gH3CVOGl+niIQIaCfPH1ZnFWeGHKd4/DP36uckTKC+LIZCFmx1bcVIqsrytnvgKLItk1O6comLfAK4dsU="
  docker_sets:
    - set: ubuntu1804-64
    - set: ubuntu1604-64
    - set: centos7-64
    - set: centos6-64
    - set: debian9-64
spec/acceptance/nodesets/ec2/amazonlinux-2016091.yml:
  delete: true
spec/acceptance/nodesets/ec2/image_templates.yaml:
  delete: true
spec/acceptance/nodesets/ec2/rhel-73-x64.yml:
  delete: true
spec/acceptance/nodesets/ec2/sles-12sp2-x64.yml:
  delete: true
spec/acceptance/nodesets/ec2/ubuntu-1604-x64.yml:
  delete: true
spec/acceptance/nodesets/ec2/windows-2016-base-x64.yml:
  delete: true
spec/acceptance/nodesets/archlinux-2-x64.yml:
  delete: true
