---
.travis.yml:
  secure: "d5y7m0AEZILPzTQU3e8G/RPwqmV1I7kqgWRRg3iR0Xxr/r0ph7LMd7Hd6/68TnQ/DAlh6bNvuw5OUmeXfz3ajg0dG5i0VUQyaCierI6PPFkOtU1/6yf7O7uLcHDDV6QC26RzjXSvZT0kkeuyFGac3azUOpOFm4FXyErsoXhmhGu1N8Mrpn4TlngDugOHM0YC2b5lGONiIz93HfMlijEWYYC+3SJXry/IoxwsNAmJRkyDLhQ7QkE3e3onz/JxXBUd4N2G5hx3ThcZUpJw8SFHqhlProqa0GeOG7EVBXuTY7t5Qln+uM+lZdOZLd+aVJLX3qk/KWohUQtA8/5mKRQVRud5ynCJoc3HR961Y13Yu8f8CYGFfwfYWkztBE7XlrJ3mV5BCPVb0I4BP+C2YgxY6wP6ZD3lm4Ur1RMvGoD+SsknG1jmsXAEP8ulhQwynfIDhqJwa7x9jWOzBrInww05/tZgUOPTD1OlAqZXwHxIvRbUBjN+BGCnmSgTqrQmF/qik5UBpBOUf+igAQDemVQSp6w0x/GJzQ0sUMXYrvIc8/p+CuP3fzwrPZpkHc7Fc7QCK8Fs+7e04GjysF4ASpEqQ9eifBg8yOeL58jiOYft9OwoetFAw36o+E5rY7qQna9eZmftyiwAA75vSFv3bqE4ujzT20JF7ALC2vVnZsmPocI="
  docker_sets:
    - set: ubuntu1804-64
    - set: ubuntu1604-64
    - set: centos7-64
    - set: centos6-64
    - set: debian9-64
    - set: debian8-64
spec/acceptance/nodesets/ec2/amazonlinux-2016091.yml:
  delete: true
spec/acceptance/nodesets/ec2/image_templates.yaml:
  delete: true
spec/acceptance/nodesets/ec2/rhel-73-x64.yml:
  delete: true
spec/acceptance/nodesets/ec2/sles-12sp2-x64.yml:
  delete: true
spec/acceptance/nodesets/ec2/ubuntu-1604-x64.yml:
  delete: true
spec/acceptance/nodesets/ec2/windows-2016-base-x64.yml:
  delete: true
spec/acceptance/nodesets/archlinux-2-x64.yml:
  delete: true
