---
dist: bionic
language: ruby
cache: bundler
before_install:
  - yes | gem update --system
  - bundle --version
script:
  - 'bundle exec rake $CHECK'
matrix:
  fast_finish: true
  include:
  - rvm: 2.4.4
    bundler_args: --without system_tests development release
    env: PUPPET_VERSION="~> 5.0" CHECK=test
  - rvm: 2.5.3
    bundler_args: --without system_tests development release
    env: PUPPET_VERSION="~> 6.0" CHECK=test_with_coveralls
  - rvm: 2.5.3
    bundler_args: --without system_tests development release
    env: PUPPET_VERSION="~> 6.0" CHECK=rubocop
  - rvm: 2.4.4
    bundler_args: --without system_tests development release
    env: PUPPET_VERSION="~> 5.0" CHECK=build DEPLOY_TO_FORGE=yes
  - rvm: 2.5.3
    bundler_args: --without development release
    env: PUPPET_INSTALL_TYPE=agent BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_debug=true BEAKER_setfile=ubuntu1804-64 BEAKER_HYPERVISOR=docker CHECK=beaker
    services: docker
  - rvm: 2.5.3
    bundler_args: --without development release
    env: PUPPET_INSTALL_TYPE=agent BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_debug=true BEAKER_setfile=ubuntu1804-64 BEAKER_HYPERVISOR=docker CHECK=beaker
    services: docker
  - rvm: 2.5.3
    bundler_args: --without development release
    env: PUPPET_INSTALL_TYPE=agent BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_debug=true BEAKER_setfile=ubuntu1604-64 BEAKER_HYPERVISOR=docker CHECK=beaker
    services: docker
  - rvm: 2.5.3
    bundler_args: --without development release
    env: PUPPET_INSTALL_TYPE=agent BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_debug=true BEAKER_setfile=ubuntu1604-64 BEAKER_HYPERVISOR=docker CHECK=beaker
    services: docker
  - rvm: 2.5.3
    bundler_args: --without development release
    env: PUPPET_INSTALL_TYPE=agent BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_debug=true BEAKER_setfile=centos7-64 BEAKER_HYPERVISOR=docker CHECK=beaker
    services: docker
  - rvm: 2.5.3
    bundler_args: --without development release
    env: PUPPET_INSTALL_TYPE=agent BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_debug=true BEAKER_setfile=centos7-64 BEAKER_HYPERVISOR=docker CHECK=beaker
    services: docker
  - rvm: 2.5.3
    bundler_args: --without development release
    env: PUPPET_INSTALL_TYPE=agent BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_debug=true BEAKER_setfile=centos6-64 BEAKER_HYPERVISOR=docker CHECK=beaker
    services: docker
  - rvm: 2.5.3
    bundler_args: --without development release
    env: PUPPET_INSTALL_TYPE=agent BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_debug=true BEAKER_setfile=centos6-64 BEAKER_HYPERVISOR=docker CHECK=beaker
    services: docker
  - rvm: 2.5.3
    bundler_args: --without development release
    env: PUPPET_INSTALL_TYPE=agent BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_debug=true BEAKER_setfile=debian9-64 BEAKER_HYPERVISOR=docker CHECK=beaker
    services: docker
  - rvm: 2.5.3
    bundler_args: --without development release
    env: PUPPET_INSTALL_TYPE=agent BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_debug=true BEAKER_setfile=debian9-64 BEAKER_HYPERVISOR=docker CHECK=beaker
    services: docker
  - rvm: 2.5.3
    bundler_args: --without development release
    env: PUPPET_INSTALL_TYPE=agent BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_debug=true BEAKER_setfile=debian8-64 BEAKER_HYPERVISOR=docker CHECK=beaker
    services: docker
  - rvm: 2.5.3
    bundler_args: --without development release
    env: PUPPET_INSTALL_TYPE=agent BEAKER_PUPPET_COLLECTION=puppet6 BEAKER_debug=true BEAKER_setfile=debian8-64 BEAKER_HYPERVISOR=docker CHECK=beaker
    services: docker
branches:
  only:
  - master
  - /^v\d/
notifications:
  email: false
  webhooks: https://voxpupu.li/incoming/travis
  irc:
    on_success: always
    on_failure: always
    channels:
      - "chat.freenode.org#voxpupuli-notifications"
deploy:
  provider: puppetforge
  user: puppet
  password:
    secure: "d5y7m0AEZILPzTQU3e8G/RPwqmV1I7kqgWRRg3iR0Xxr/r0ph7LMd7Hd6/68TnQ/DAlh6bNvuw5OUmeXfz3ajg0dG5i0VUQyaCierI6PPFkOtU1/6yf7O7uLcHDDV6QC26RzjXSvZT0kkeuyFGac3azUOpOFm4FXyErsoXhmhGu1N8Mrpn4TlngDugOHM0YC2b5lGONiIz93HfMlijEWYYC+3SJXry/IoxwsNAmJRkyDLhQ7QkE3e3onz/JxXBUd4N2G5hx3ThcZUpJw8SFHqhlProqa0GeOG7EVBXuTY7t5Qln+uM+lZdOZLd+aVJLX3qk/KWohUQtA8/5mKRQVRud5ynCJoc3HR961Y13Yu8f8CYGFfwfYWkztBE7XlrJ3mV5BCPVb0I4BP+C2YgxY6wP6ZD3lm4Ur1RMvGoD+SsknG1jmsXAEP8ulhQwynfIDhqJwa7x9jWOzBrInww05/tZgUOPTD1OlAqZXwHxIvRbUBjN+BGCnmSgTqrQmF/qik5UBpBOUf+igAQDemVQSp6w0x/GJzQ0sUMXYrvIc8/p+CuP3fzwrPZpkHc7Fc7QCK8Fs+7e04GjysF4ASpEqQ9eifBg8yOeL58jiOYft9OwoetFAw36o+E5rY7qQna9eZmftyiwAA75vSFv3bqE4ujzT20JF7ALC2vVnZsmPocI="
  on:
    tags: true
    # all_branches is required to use tags
    all_branches: true
    # Only publish the build marked with "DEPLOY_TO_FORGE"
    condition: "$DEPLOY_TO_FORGE = yes"
